dist: trusty
addons:
  postgresql: "9.6"
language: go
services:
  - postgresql
go:
  - "1.12"
jobs:
  include:
    - stage: build
      script: make
    - stage: test
      script: make test
    - stage: lint
      script: make lint
env:
  global:
    - GO111MODULE=on
