[package]
name = "krumnet"
version = "0.1.0"
authors = ["Danny Hadley <dadleyy@gmail.com>"]
edition = "2018"

[lib]
name = "krumnet"
path = "src/lib.rs"

[[bin]]
name = "krumnet"
path = "src/bin/main.rs"

[dependencies]
async-std = "^0.99"
http = "^0.1"
url = "^2.1"
chrono = "^0.4"
chrono-tz = "^0.5"
gumdrop = "^0.7"
serde_json = "^1.0"
isahc = "^0.7.4"

[dependencies.serde]
version = "^1.0"
features = ["derive"]
