name: gh.build-and-test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: krumnet-test
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 10
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v1
      - name: pg-dev postgresql-client-11
        run: sudo apt-get -y install libpq-dev
      - name: check-ready
        env:
          POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
        run: pg_isready --username postgres --host postgres --port $POSTGRES_PORT --timeout 10
      - name: create-db
        run: createdb --port=5432 --host=postgres krumnet-test
      - name: install-beta
        run: rustup toolchain install beta
      - name: use-beta
        run: rustup default beta
      - name: build
        run: cargo build
      - name: test
        run: cargo test --verbose -- --nocapture
