name: gh.build-and-test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: krumnet-test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v1
      - name: check-ready
        run: pg_isready
      - name: create-db
        run: createdb krumnet-test
      - name: install-beta
        run: rustup toolchain install beta
      - name: use-beta
        run: rustup default beta
      - name: build
        run: cargo build
      - name: test
        run: cargo test --verbose -- --nocapture
