name: gh.build-and-test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image:  rust:1.43.0
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v1
      - name: Install postgres packages
        run: apt-get -y install libpq-dev
      - name: List github files
        run: ls -lah .github/
      - name: Rustup install beta
        run: rustup toolchain install beta
      - name: Rustup use beta
        run: rustup default beta
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test --verbose -- --nocapture
        env:
          KRUMNET_TEST_CONFIG_FILE: .github/krumnet-config.json
