name: gh.build-and-test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11.5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: krumnet-test
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 10
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v1
      - name: pg-packages
        run: sudo apt-get -y install libpq-dev postgresql-client
      - name: install-beta
        run: rustup toolchain install beta
      - name: use-beta
        run: rustup default beta
      - name: build
        run: cargo build
      - name: test
        run: cargo test --verbose -- --nocapture
